version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule: { interval: weekly }
    open-pull-requests-limit: 10
    groups:
      eslint:
        patterns: ["eslint*", "@typescript-eslint/*"]
      prisma:
        patterns: ["prisma", "@prisma/*"]
      next:
        patterns: ["next", "react", "react-dom"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: "/infra/docker"
    schedule: { interval: weekly }
